bot:
  joint_state_controller:
      type: "joint_state_controller/JointStateController"
      publish_rate: 50

  bot_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['left_wheel_0_joint', 'left_wheel_1_joint', 'left_wheel_2_joint', 'left_wheel_3_joint']   
    left_wheel_rev: ['left_wheel_0_rev', 'left_wheel_1_rev', 'left_wheel_2_rev', 'left_wheel_3_rev']
    right_wheel: ['right_wheel_0_joint', 'right_wheel_1_joint', 'right_wheel_2_joint', 'right_wheel_3_joint']
    right_wheel_rev: ['right_wheel_0_rev', 'right_wheel_1_rev', 'right_wheel_2_rev', 'right_wheel_3_rev']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    cmd_vel_timeout: 0.55

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.8 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 30.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 20.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 25.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 25.0   # rad/s^2

