bot:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  left_wheel_0_joint:
    type: velocity_controllers/JointVelocityController
    joint: left_wheel_0_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  left_wheel_1_joint:
    type: velocity_controllers/JointVelocityController
    joint: left_wheel_1_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  left_wheel_2_joint:
    type: velocity_controllers/JointVelocityController
    joint: left_wheel_2_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  left_wheel_3_joint:
    type: velocity_controllers/JointVelocityController
    joint: left_wheel_3_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  right_wheel_0_joint:
    type: velocity_controllers/JointVelocityController
    joint: right_wheel_0_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  right_wheel_1_joint:
    type: velocity_controllers/JointVelocityController
    joint: right_wheel_1_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  right_wheel_2_joint:
    type: velocity_controllers/JointVelocityController
    joint: right_wheel_2_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}

  right_wheel_3_joint:
    type: velocity_controllers/JointVelocityController
    joint: right_wheel_3_joint
    pid: {p: 100.0, i: 0.01, d: 1.0}
